name: Audit

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master", "develop"]

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
  check-broken-dependencies:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Audit with pip
        run: |
          pip check
  audit-with-pip:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Audit with pip
        run: |
          pip list --outdated
  audit-with-safety:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Audit with safety
        run: |
          safety check
  audit-with-pip-audit:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Audit with pip-audit
        uses: pypa/gh-action-pip-audit@v1.0.8
