name: Lint and Test

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master", "develop"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v3
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Exports all Github Environment Secrets
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - name: Exports all Github Environment Variables
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(vars) }}
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --statistics
      - name: Prepare reports directory
        run: |
          mkdir -p reports
          touch reports/pytest.xml
          touch reports/pytest-coverage.txt
      - name: Run tests with pytest
        run: |
          # make sure pipe propogates exit code to fail on test failure
          set -o pipefail
          pytest --junitxml=reports/pytest.xml --cov-report=term-missing:skip-covered --cov=server tests/ | tee reports/pytest-coverage.txt
          set +o pipefail
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: reports/pytest-coverage.txt
          junitxml-path: reports/pytest.xml
