name: Lint

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master", "develop"]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  lint-with-flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Check syntax first with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Run linter and comment PR
        uses: matias-martini/flake8-pr-comments-action@main
        with:
          github_token: ${{ github.token }}
          cfg_path: ".flake8"
