name: Test

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master", "develop"]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  test-with-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Exports all Github Environment Secrets
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - name: Exports all Github Environment Variables
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(vars) }}
      - name: Prepare reports directory
        run: |
          mkdir -p reports
          touch reports/pytest.xml
          touch reports/pytest-coverage.txt
      - name: Run tests with pytest
        run: |
          # make sure pipe propogates exit code to fail on test failure
          set -o pipefail
          pytest --junitxml=reports/pytest.xml --cov-report=term-missing:skip-covered --cov=server tests/ | tee reports/pytest-coverage.txt
          set +o pipefail
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: reports/pytest-coverage.txt
          junitxml-path: reports/pytest.xml
